

GET http://localhost:5093
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFjY2VyIiwic3ViIjoiYWNjZXIiLCJqdGkiOiJjMDdjNTlhNCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwOTMiLCJodHRwczovL2xvY2FsaG9zdDo3MDMwIl0sIm5iZiI6MTc1ODE5Nzk1MCwiZXhwIjoxNzY2MDYwMzUwLCJpYXQiOjE3NTgxOTc5NTEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.ubtQ7Dvxyd-wiCJ1sISLm224kqPIbqHIfi6enPIQ62k